In [1]:
# importing the requried librabies
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# creating a dataframe 
train_df=pd.read_csv(r"C:\Users\admin\Downloads\train_df.csv")
test_df=pd.read_csv(r"C:\Users\admin\Downloads\test_df.csv")

C:\Users\admin\AppData\Local\Temp\ipykernel_4056\3414869663.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df=pd.read_csv(r"C:\Users\admin\Downloads\train_df.csv")

In [3]:
#printing top 10 rows of the dataframe
train_df.head(10)

,Id,County,Province_State,Country_Region,Population,Weight,Date,Target,TargetValue
0,1,NaN,NaN,Afghanistan,27657145,0.058359,23-01-2020,ConfirmedCases,0
1,2,NaN,NaN,Afghanistan,27657145,0.583587,23-01-2020,Fatalities,0
2,3,NaN,NaN,Afghanistan,27657145,0.058359,24-01-2020,ConfirmedCases,0
3,4,NaN,NaN,Afghanistan,27657145,0.583587,24-01-2020,Fatalities,0
4,5,NaN,NaN,Afghanistan,27657145,0.058359,25-01-2020,ConfirmedCases,0
5,6,NaN,NaN,Afghanistan,27657145,0.583587,25-01-2020,Fatalities,0
6,7,NaN,NaN,Afghanistan,27657145,0.058359,26-01-2020,ConfirmedCases,0
7,8,NaN,NaN,Afghanistan,27657145,0.583587,26-01-2020,Fatalities,0
8,9,NaN,NaN,Afghanistan,27657145,0.058359,27-01-2020,ConfirmedCases,0
9,10,NaN,NaN,Afghanistan,27657145,0.583587,27-01-2020,Fatalities,0

In [4]:
test_df.head(10)

,ForecastId,County,Province_State,Country_Region,Population,Weight,Date,Target
0,1,NaN,NaN,Afghanistan,27657145,0.058359,27-04-2020,ConfirmedCases
1,2,NaN,NaN,Afghanistan,27657145,0.583587,27-04-2020,Fatalities
2,3,NaN,NaN,Afghanistan,27657145,0.058359,28-04-2020,ConfirmedCases
3,4,NaN,NaN,Afghanistan,27657145,0.583587,28-04-2020,Fatalities
4,5,NaN,NaN,Afghanistan,27657145,0.058359,29-04-2020,ConfirmedCases
5,6,NaN,NaN,Afghanistan,27657145,0.583587,29-04-2020,Fatalities
6,7,NaN,NaN,Afghanistan,27657145,0.058359,30-04-2020,ConfirmedCases
7,8,NaN,NaN,Afghanistan,27657145,0.583587,30-04-2020,Fatalities
8,9,NaN,NaN,Afghanistan,27657145,0.058359,01-05-2020,ConfirmedCases
9,10,NaN,NaN,Afghanistan,27657145,0.583587,01-05-2020,Fatalities

In [5]:
# to get the summary of the dataframe
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 969640 entries, 0 to 969639
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Id              969640 non-null  int64
 1   County          880040 non-null  object
 2   Province_State  917280 non-null  object
 3   Country_Region  969640 non-null  object
 4   Population      969640 non-null  int64
 5   Weight          969640 non-null  float64
 6   Date            969640 non-null  object
 7   Target          969640 non-null  object
 8   TargetValue     969640 non-null  int64
dtypes: float64(1), int64(3), object(5)
memory usage: 66.6+ MB

here, we can clearly see our data contains total 9 columns and total 969640 rows with some missing values in column country and province_state

In [6]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311670 entries, 0 to 311669
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ForecastId      311670 non-null  int64
 1   County          282870 non-null  object
 2   Province_State  294840 non-null  object
 3   Country_Region  311670 non-null  object
 4   Population      311670 non-null  int64
 5   Weight          311670 non-null  float64
 6   Date            311670 non-null  object
 7   Target          311670 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 19.0+ MB

as we can see in the above shell our data contains total 8 columns and total 311670 rows with some missing values in column country and province_state

In [7]:
for i in test_df.columns:
    print(f"Unique{i}'s count:{test_df[i].nunique()}")
    print(f"{test_df[i].unique()}\n")

UniqueForecastId's count:311670
[     1      2      3 ... 311668 311669 311670]

UniqueCounty's count:1840
[nan 'Autauga' 'Baldwin' ... 'Uinta' 'Washakie' 'Weston']

UniqueProvince_State's count:133
[nan 'Australian Capital Territory' 'New South Wales' 'Northern Territory'
 'Queensland' 'South Australia' 'Tasmania' 'Victoria' 'Western Australia'
 'Alberta' 'British Columbia' 'Manitoba' 'New Brunswick'
 'Newfoundland and Labrador' 'Northwest Territories' 'Nova Scotia'
 'Ontario' 'Prince Edward Island' 'Quebec' 'Saskatchewan' 'Yukon' 'Anhui'
 'Beijing' 'Chongqing' 'Fujian' 'Gansu' 'Guangdong' 'Guangxi' 'Guizhou'
 'Hainan' 'Hebei' 'Heilongjiang' 'Henan' 'Hong Kong' 'Hubei' 'Hunan'
 'Inner Mongolia' 'Jiangsu' 'Jiangxi' 'Jilin' 'Liaoning' 'Macau' 'Ningxia'
 'Qinghai' 'Shaanxi' 'Shandong' 'Shanghai' 'Shanxi' 'Sichuan' 'Tianjin'
 'Tibet' 'Xinjiang' 'Yunnan' 'Zhejiang' 'Faroe Islands' 'Greenland'
 'French Guiana' 'French Polynesia' 'Guadeloupe' 'Martinique' 'Mayotte'
 'New Caledonia' 'Reunion' 'Saint Barthelemy' 'Saint Pierre and Miquelon'
 'St Martin' 'Aruba' 'Bonaire, Sint Eustatius and Saba' 'Curacao'
 'Sint Maarten' 'Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California'
 'Colorado' 'Connecticut' 'Delaware' 'District of Columbia' 'Florida'
 'Georgia' 'Guam' 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas'
 'Kentucky' 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan'
 'Minnesota' 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada'
 'New Hampshire' 'New Jersey' 'New Mexico' 'New York' 'North Carolina'
 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Puerto Rico'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virgin Islands' 'Virginia' 'Washington' 'West Virginia'
 'Wisconsin' 'Wyoming' 'Anguilla' 'Bermuda' 'British Virgin Islands'
 'Cayman Islands' 'Channel Islands' 'Falkland Islands (Malvinas)'
 'Gibraltar' 'Isle of Man' 'Montserrat' 'Turks and Caicos Islands']

UniqueCountry_Region's count:187
['Afghanistan' 'Albania' 'Algeria' 'Andorra' 'Angola'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Australia' 'Austria'
 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus'
 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina'
 'Botswana' 'Brazil' 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burma' 'Burundi'
 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada' 'Central African Republic'
 'Chad' 'Chile' 'China' 'Colombia' 'Comoros' 'Congo (Brazzaville)'
 'Congo (Kinshasa)' 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba' 'Cyprus'
 'Czechia' 'Denmark' 'Diamond Princess' 'Djibouti' 'Dominica'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'Equatorial Guinea'
 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Fiji' 'Finland' 'France'
 'Gabon' 'Gambia' 'Georgia' 'Germany' 'Ghana' 'Greece' 'Grenada'
 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Holy See'
 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq'
 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan'
 'Kenya' 'Korea, South' 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia'
 'Lebanon' 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Luxembourg'
 'MS Zaandam' 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Mauritania' 'Mauritius' 'Mexico' 'Moldova' 'Monaco' 'Mongolia'
 'Montenegro' 'Morocco' 'Mozambique' 'Namibia' 'Nepal' 'Netherlands'
 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'North Macedonia' 'Norway'
 'Oman' 'Pakistan' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Qatar' 'Romania' 'Russia' 'Rwanda'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Vincent and the Grenadines'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia'
 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia' 'Somalia'
 'South Africa' 'South Sudan' 'Spain' 'Sri Lanka' 'Sudan' 'Suriname'
 'Sweden' 'Switzerland' 'Syria' 'Taiwan*' 'Tajikistan' 'Tanzania'
 'Thailand' 'Timor-Leste' 'Togo' 'Trinidad and Tobago' 'Tunisia' 'Turkey'
 'US' 'Uganda' 'Ukraine' 'United Arab Emirates' 'United Kingdom' 'Uruguay'
 'Uzbekistan' 'Venezuela' 'Vietnam' 'West Bank and Gaza' 'Western Sahara'
 'Yemen' 'Zambia' 'Zimbabwe']

UniquePopulation's count:3408
[27657145  2886026 40400000 ... 28500000 15933883 14240168]

UniqueWeight's count:6816
[0.05835874 0.58358737 0.06722512 ... 0.60299234 0.06071064 0.6071064 ]

UniqueDate's count:45
['27-04-2020' '28-04-2020' '29-04-2020' '30-04-2020' '01-05-2020'
 '02-05-2020' '03-05-2020' '04-05-2020' '05-05-2020' '06-05-2020'
 '07-05-2020' '08-05-2020' '09-05-2020' '10-05-2020' '11-05-2020'
 '12-05-2020' '13-05-2020' '14-05-2020' '15-05-2020' '16-05-2020'
 '17-05-2020' '18-05-2020' '19-05-2020' '20-05-2020' '21-05-2020'
 '22-05-2020' '23-05-2020' '24-05-2020' '25-05-2020' '26-05-2020'
 '27-05-2020' '28-05-2020' '29-05-2020' '30-05-2020' '31-05-2020'
 '01-06-2020' '02-06-2020' '03-06-2020' '04-06-2020' '05-06-2020'
 '06-06-2020' '07-06-2020' '08-06-2020' '09-06-2020' '10-06-2020']

UniqueTarget's count:2
['ConfirmedCases' 'Fatalities']

In [8]:
for i in train_df.columns:
    print(f"Unique{i}'s count:{train_df[i].nunique()}")
    print(f"{train_df[i].unique()}\n")

UniqueId's count:969640
[     1      2      3 ... 969638 969639 969640]

UniqueCounty's count:1840
[nan 'Autauga' 'Baldwin' ... 'Uinta' 'Washakie' 'Weston']

UniqueProvince_State's count:133
[nan 'Australian Capital Territory' 'New South Wales' 'Northern Territory'
 'Queensland' 'South Australia' 'Tasmania' 'Victoria' 'Western Australia'
 'Alberta' 'British Columbia' 'Manitoba' 'New Brunswick'
 'Newfoundland and Labrador' 'Northwest Territories' 'Nova Scotia'
 'Ontario' 'Prince Edward Island' 'Quebec' 'Saskatchewan' 'Yukon' 'Anhui'
 'Beijing' 'Chongqing' 'Fujian' 'Gansu' 'Guangdong' 'Guangxi' 'Guizhou'
 'Hainan' 'Hebei' 'Heilongjiang' 'Henan' 'Hong Kong' 'Hubei' 'Hunan'
 'Inner Mongolia' 'Jiangsu' 'Jiangxi' 'Jilin' 'Liaoning' 'Macau' 'Ningxia'
 'Qinghai' 'Shaanxi' 'Shandong' 'Shanghai' 'Shanxi' 'Sichuan' 'Tianjin'
 'Tibet' 'Xinjiang' 'Yunnan' 'Zhejiang' 'Faroe Islands' 'Greenland'
 'French Guiana' 'French Polynesia' 'Guadeloupe' 'Martinique' 'Mayotte'
 'New Caledonia' 'Reunion' 'Saint Barthelemy' 'Saint Pierre and Miquelon'
 'St Martin' 'Aruba' 'Bonaire, Sint Eustatius and Saba' 'Curacao'
 'Sint Maarten' 'Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California'
 'Colorado' 'Connecticut' 'Delaware' 'District of Columbia' 'Florida'
 'Georgia' 'Guam' 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas'
 'Kentucky' 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan'
 'Minnesota' 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada'
 'New Hampshire' 'New Jersey' 'New Mexico' 'New York' 'North Carolina'
 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Puerto Rico'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virgin Islands' 'Virginia' 'Washington' 'West Virginia'
 'Wisconsin' 'Wyoming' 'Anguilla' 'Bermuda' 'British Virgin Islands'
 'Cayman Islands' 'Channel Islands' 'Falkland Islands (Malvinas)'
 'Gibraltar' 'Isle of Man' 'Montserrat' 'Turks and Caicos Islands']

UniqueCountry_Region's count:187
['Afghanistan' 'Albania' 'Algeria' 'Andorra' 'Angola'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Australia' 'Austria'
 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus'
 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina'
 'Botswana' 'Brazil' 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burma' 'Burundi'
 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada' 'Central African Republic'
 'Chad' 'Chile' 'China' 'Colombia' 'Comoros' 'Congo (Brazzaville)'
 'Congo (Kinshasa)' 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba' 'Cyprus'
 'Czechia' 'Denmark' 'Diamond Princess' 'Djibouti' 'Dominica'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'Equatorial Guinea'
 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Fiji' 'Finland' 'France'
 'Gabon' 'Gambia' 'Georgia' 'Germany' 'Ghana' 'Greece' 'Grenada'
 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Holy See'
 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq'
 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan'
 'Kenya' 'Korea, South' 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia'
 'Lebanon' 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Luxembourg'
 'MS Zaandam' 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Mauritania' 'Mauritius' 'Mexico' 'Moldova' 'Monaco' 'Mongolia'
 'Montenegro' 'Morocco' 'Mozambique' 'Namibia' 'Nepal' 'Netherlands'
 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'North Macedonia' 'Norway'
 'Oman' 'Pakistan' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Qatar' 'Romania' 'Russia' 'Rwanda'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Vincent and the Grenadines'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia'
 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia' 'Somalia'
 'South Africa' 'South Sudan' 'Spain' 'Sri Lanka' 'Sudan' 'Suriname'
 'Sweden' 'Switzerland' 'Syria' 'Taiwan*' 'Tajikistan' 'Tanzania'
 'Thailand' 'Timor-Leste' 'Togo' 'Trinidad and Tobago' 'Tunisia' 'Turkey'
 'US' 'Uganda' 'Ukraine' 'United Arab Emirates' 'United Kingdom' 'Uruguay'
 'Uzbekistan' 'Venezuela' 'Vietnam' 'West Bank and Gaza' 'Western Sahara'
 'Yemen' 'Zambia' 'Zimbabwe']

UniquePopulation's count:3408
[27657145  2886026 40400000 ... 28500000 15933883 14240168]

UniqueWeight's count:6816
[0.05835874 0.58358737 0.06722512 ... 0.60299234 0.06071064 0.6071064 ]

UniqueDate's count:140
['23-01-2020' '24-01-2020' '25-01-2020' '26-01-2020' '27-01-2020'
 '28-01-2020' '29-01-2020' '30-01-2020' '31-01-2020' '01-02-2020'
 '02-02-2020' '03-02-2020' '04-02-2020' '05-02-2020' '06-02-2020'
 '07-02-2020' '08-02-2020' '09-02-2020' '10-02-2020' '11-02-2020'
 '12-02-2020' '13-02-2020' '14-02-2020' '15-02-2020' '16-02-2020'
 '17-02-2020' '18-02-2020' '19-02-2020' '20-02-2020' '21-02-2020'
 '22-02-2020' '23-02-2020' '24-02-2020' '25-02-2020' '26-02-2020'
 '27-02-2020' '28-02-2020' '29-02-2020' '01-03-2020' '02-03-2020'
 '03-03-2020' '04-03-2020' '05-03-2020' '06-03-2020' '07-03-2020'
 '08-03-2020' '09-03-2020' '10-03-2020' '11-03-2020' '12-03-2020'
 '13-03-2020' '14-03-2020' '15-03-2020' '16-03-2020' '17-03-2020'
 '18-03-2020' '19-03-2020' '20-03-2020' '21-03-2020' '22-03-2020'
 '23-03-2020' '24-03-2020' '25-03-2020' '26-03-2020' '27-03-2020'
 '28-03-2020' '29-03-2020' '30-03-2020' '31-03-2020' '01-04-2020'
 '02-04-2020' '03-04-2020' '04-04-2020' '05-04-2020' '06-04-2020'
 '07-04-2020' '08-04-2020' '09-04-2020' '10-04-2020' '11-04-2020'
 '12-04-2020' '13-04-2020' '14-04-2020' '15-04-2020' '16-04-2020'
 '17-04-2020' '18-04-2020' '19-04-2020' '20-04-2020' '21-04-2020'
 '22-04-2020' '23-04-2020' '24-04-2020' '25-04-2020' '26-04-2020'
 '27-04-2020' '28-04-2020' '29-04-2020' '30-04-2020' '01-05-2020'
 '02-05-2020' '03-05-2020' '04-05-2020' '05-05-2020' '06-05-2020'
 '07-05-2020' '08-05-2020' '09-05-2020' '10-05-2020' '11-05-2020'
 '12-05-2020' '13-05-2020' '14-05-2020' '15-05-2020' '16-05-2020'
 '17-05-2020' '18-05-2020' '19-05-2020' '20-05-2020' '21-05-2020'
 '22-05-2020' '23-05-2020' '24-05-2020' '25-05-2020' '26-05-2020'
 '27-05-2020' '28-05-2020' '29-05-2020' '30-05-2020' '31-05-2020'
 '01-06-2020' '02-06-2020' '03-06-2020' '04-06-2020' '05-06-2020'
 '06-06-2020' '07-06-2020' '08-06-2020' '09-06-2020' '10-06-2020']

UniqueTarget's count:2
['ConfirmedCases' 'Fatalities']

UniqueTargetValue's count:2603
[   0    1    3 ... 1650 1326  -21]

In [ ]:
train_df[]